from rest_framework import serializers
from organizations.models import Branch, Company
from ..models import WhatsAppNumber

# Define your monitoring serializers here.

class MonitoringWhatsAppNumberSerializer(serializers.ModelSerializer):
    """
        DOCSTRING: Monitoring WhatsApp Number Serializer

        Description:
        - Provide the compact WhatsApp number representation required by the monitoring context selector.

        Notes:
        - Only operational information required by the monitoring frontend is exposed.
        - Sensitive Meta identifiers and credentials are intentionally excluded.
        - The serializer is strictly read-only.
    """

    class Meta:
        model = WhatsAppNumber
        fields = [
            "id",
            "display_name",
            "phone_number",
            "is_connected",
            "is_monitoring_enabled",
        ]
        read_only_fields = fields


class MonitoringBranchSerializer(serializers.ModelSerializer):
    """
        DOCSTRING: Monitoring Branch Serializer

        Description:
        - Provide a branch representation together with WhatsApp numbers available for monitoring.

        Notes:
        - Numbers are supplied through a prefetched attribute generated by MonitoringContextView.
        - Only active and monitoring-enabled numbers are included.
        - The serializer is strictly read-only.
    """

    numbers = serializers.SerializerMethodField()

    class Meta:
        model = Branch
        fields = [
            "id",
            "name",
            "code",
            "numbers",
        ]
        read_only_fields = fields

    def get_numbers(self, obj):
        numbers = getattr(
            obj,
            "monitoring_numbers",
            [],
        )

        return MonitoringWhatsAppNumberSerializer(
            numbers,
            many=True,
        ).data


class MonitoringCompanySerializer(serializers.ModelSerializer):
    """
        DOCSTRING: Monitoring Company Serializer

        Description:
        - Provide the company hierarchy available to an authenticated monitoring user.
        - Include active branches containing operational WhatsApp numbers.

        Notes:
        - Branches are supplied through a prefetched attribute generated by MonitoringContextView.
        - Company authorization is determined by active company-access records.
        - The serializer is strictly read-only.
    """

    branches = serializers.SerializerMethodField()

    class Meta:
        model = Company
        fields = [
            "id",
            "name",
            "code",
            "branches",
        ]
        read_only_fields = fields

    def get_branches(self, obj):
        branches = getattr(
            obj,
            "monitoring_branches",
            [],
        )

        return MonitoringBranchSerializer(
            branches,
            many=True,
        ).data