# Generated by Django 6.1 on 2026-08-24 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('ACCESS', 'Access'), ('ORGANIZATION', 'Organization'), ('MEMBER', 'Member'), ('WHATSAPP', 'WhatsApp'), ('META', 'Meta'), ('SECURITY', 'Security'), ('SYSTEM', 'System')], max_length=30)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('CONNECT', 'Connect'), ('DISCONNECT', 'Disconnect'), ('VALIDATE', 'Validate'), ('OPEN', 'Open'), ('READ', 'Read'), ('SEND', 'Send'), ('SYNCHRONIZE', 'Synchronize'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('GRANT', 'Grant'), ('REVOKE', 'Revoke')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('target_app', models.CharField(blank=True, default='', max_length=100)),
                ('target_model', models.CharField(blank=True, default='', max_length=150)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.company')),
            ],
            options={
                'db_table': 'auditing_event',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['company', 'occurred_at'], name='idx_audit_company_time'), models.Index(fields=['company', 'category'], name='idx_audit_company_category'), models.Index(fields=['company', 'action'], name='idx_audit_company_action'), models.Index(fields=['company', 'severity'], name='idx_audit_company_severity'), models.Index(fields=['actor', 'occurred_at'], name='idx_audit_actor_time'), models.Index(fields=['branch', 'occurred_at'], name='idx_audit_branch_time'), models.Index(fields=['target_app', 'target_model', 'target_id'], name='idx_audit_target'), models.Index(fields=['request_id'], name='idx_audit_request')],
            },
        ),
    ]
