# Generated by Django 6.1 on 2026-08-21 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('profile_name', models.CharField(blank=True, default='', max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_customer',
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='whatsapp.customer')),
            ],
            options={
                'db_table': 'whatsapp_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_message_id', models.CharField(max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('STICKER', 'Sticker'), ('EDIT', 'Edit'), ('REVOKE', 'Revoke'), ('UNSUPPORTED', 'Unsupported')], max_length=20)),
                ('sender_phone_number', models.CharField(max_length=30)),
                ('recipient_phone_number', models.CharField(max_length=30)),
                ('text_body', models.TextField(blank=True, default='')),
                ('message_timestamp', models.DateTimeField()),
                ('meta_event_timestamp', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='whatsapp.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('edited_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edit_events', to='whatsapp.message')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_message',
                'ordering': ['message_timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_media_id', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(max_length=150)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('checksum', models.CharField(blank=True, default='', max_length=255)),
                ('is_stored', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_attachments', to='whatsapp.message')),
            ],
            options={
                'db_table': 'whatsapp_media_attachment',
            },
        ),
        migrations.CreateModel(
            name='ConversationReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='whatsapp.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversation_read_states', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.message')),
            ],
            options={
                'db_table': 'whatsapp_conversation_read_state',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.message'),
        ),
        migrations.CreateModel(
            name='MetaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_app_id', models.CharField(max_length=100)),
                ('credential_reference', models.CharField(max_length=255, unique=True)),
                ('webhook_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_integrations', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_meta_integration',
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_waba_id', models.CharField(max_length=100, unique=True)),
                ('meta_business_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_webhook_configured', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_business_accounts', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('meta_integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_business_accounts', to='whatsapp.metaintegration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_business_account',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('meta_phone_number_id', models.CharField(max_length=100, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_monitoring_enabled', models.BooleanField(default=False)),
                ('monitoring_started_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_numbers', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_numbers', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_business_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'db_table': 'whatsapp_number',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='NumberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_number_assignments', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='whatsapp.whatsappnumber')),
            ],
            options={
                'db_table': 'whatsapp_number_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='whatsapp.whatsappnumber'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_active'], name='idx_customer_company_active'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone_number'], name='idx_customer_company_phone'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'phone_number'), name='unique_customer_phone_per_company'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'message_timestamp'], name='idx_message_conversation_time'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction', 'message_timestamp'], name='idx_message_direction_time'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'message_timestamp'], name='idx_message_type_time'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['message', 'is_active'], name='idx_media_message_active'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['meta_media_id'], name='idx_media_meta_id'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['is_stored'], name='idx_media_stored'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['user', 'is_read'], name='idx_read_state_user_read'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['conversation', 'user'], name='idx_readstate_conv_user'),
        ),
        migrations.AddConstraint(
            model_name='conversationreadstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_read_state_per_user'),
        ),
        migrations.AddIndex(
            model_name='metaintegration',
            index=models.Index(fields=['company', 'is_active'], name='idx_meta_company_active'),
        ),
        migrations.AddIndex(
            model_name='metaintegration',
            index=models.Index(fields=['webhook_key'], name='idx_meta_webhook_key'),
        ),
        migrations.AddConstraint(
            model_name='metaintegration',
            constraint=models.UniqueConstraint(fields=('company', 'meta_app_id'), name='unique_company_meta_app'),
        ),
        migrations.AddIndex(
            model_name='whatsappbusinessaccount',
            index=models.Index(fields=['company', 'is_active'], name='idx_waba_company_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappbusinessaccount',
            index=models.Index(fields=['meta_integration', 'is_active'], name='idx_waba_meta_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappbusinessaccount',
            index=models.Index(fields=['company', 'is_connected'], name='idx_waba_company_connected'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['company', 'is_active'], name='idx_wa_number_company_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['branch', 'is_active'], name='idx_wa_number_branch_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['whatsapp_business_account', 'is_active'], name='idx_wa_number_waba_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['meta_phone_number_id'], name='idx_wa_number_meta_id'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['company', 'is_monitoring_enabled'], name='idx_wa_number_monitoring'),
        ),
        migrations.AddIndex(
            model_name='numberassignment',
            index=models.Index(fields=['whatsapp_number', 'is_active'], name='idx_assignment_number_active'),
        ),
        migrations.AddIndex(
            model_name='numberassignment',
            index=models.Index(fields=['member', 'is_active'], name='idx_assignment_member_active'),
        ),
        migrations.AddIndex(
            model_name='numberassignment',
            index=models.Index(fields=['whatsapp_number', 'assigned_at'], name='idx_assignment_number_date'),
        ),
        migrations.AddConstraint(
            model_name='numberassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('whatsapp_number',), name='unique_active_whatsapp_number_assignment'),
        ),
        migrations.AddConstraint(
            model_name='numberassignment',
            constraint=models.CheckConstraint(condition=models.Q(('unassigned_at__isnull', True), ('unassigned_at__gte', models.F('assigned_at')), _connector='OR'), name='assignment_unassigned_after_assigned'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['whatsapp_number', 'is_active'], name='idx_conversation_number_active'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['whatsapp_number', 'last_message_at'], name='idx_conversation_number_last'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', 'last_message_at'], name='idx_conversation_customer_last'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('whatsapp_number', 'customer'), name='unique_conversation_per_number_customer'),
        ),
    ]
