# Generated by Django 6.1 on 2026-08-19 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_waba_id', models.CharField(max_length=100, unique=True)),
                ('meta_business_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('credential_reference', models.CharField(max_length=255)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_webhook_configured', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_business_accounts', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_business_account',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('meta_phone_number_id', models.CharField(max_length=100, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_monitoring_enabled', models.BooleanField(default=False)),
                ('monitoring_started_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_numbers', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_numbers', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_business_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'db_table': 'whatsapp_number',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='NumberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_number_assignments', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='whatsapp.whatsappnumber')),
            ],
            options={
                'db_table': 'whatsapp_number_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappbusinessaccount',
            index=models.Index(fields=['company', 'is_active'], name='idx_waba_company_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappbusinessaccount',
            index=models.Index(fields=['company', 'is_connected'], name='idx_waba_company_connected'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['company', 'is_active'], name='idx_wa_number_company_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['branch', 'is_active'], name='idx_wa_number_branch_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['whatsapp_business_account', 'is_active'], name='idx_wa_number_waba_active'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['meta_phone_number_id'], name='idx_wa_number_meta_id'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['company', 'is_monitoring_enabled'], name='idx_wa_number_monitoring'),
        ),
        migrations.AddIndex(
            model_name='numberassignment',
            index=models.Index(fields=['whatsapp_number', 'is_active'], name='idx_assignment_number_active'),
        ),
        migrations.AddIndex(
            model_name='numberassignment',
            index=models.Index(fields=['member', 'is_active'], name='idx_assignment_member_active'),
        ),
        migrations.AddIndex(
            model_name='numberassignment',
            index=models.Index(fields=['whatsapp_number', 'assigned_at'], name='idx_assignment_number_date'),
        ),
        migrations.AddConstraint(
            model_name='numberassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('whatsapp_number',), name='unique_active_whatsapp_number_assignment'),
        ),
        migrations.AddConstraint(
            model_name='numberassignment',
            constraint=models.CheckConstraint(condition=models.Q(('unassigned_at__isnull', True), ('unassigned_at__gte', models.F('assigned_at')), _connector='OR'), name='assignment_unassigned_after_assigned'),
        ),
    ]
