# Generated by Django 6.1 on 2026-08-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappbusinessaccount',
            name='credential_reference',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('profile_name', models.CharField(blank=True, default='', max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_customer',
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='whatsapp.whatsappnumber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='whatsapp.customer')),
            ],
            options={
                'db_table': 'whatsapp_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_message_id', models.CharField(max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('STICKER', 'Sticker'), ('EDIT', 'Edit'), ('REVOKE', 'Revoke'), ('UNSUPPORTED', 'Unsupported')], max_length=20)),
                ('sender_phone_number', models.CharField(max_length=30)),
                ('recipient_phone_number', models.CharField(max_length=30)),
                ('text_body', models.TextField(blank=True, default='')),
                ('message_timestamp', models.DateTimeField()),
                ('meta_event_timestamp', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='whatsapp.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('edited_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edit_events', to='whatsapp.message')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_message',
                'ordering': ['message_timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_media_id', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(max_length=150)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('checksum', models.CharField(blank=True, default='', max_length=255)),
                ('is_stored', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_attachments', to='whatsapp.message')),
            ],
            options={
                'db_table': 'whatsapp_media_attachment',
            },
        ),
        migrations.CreateModel(
            name='ConversationReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='whatsapp.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversation_read_states', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.message')),
            ],
            options={
                'db_table': 'whatsapp_conversation_read_state',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.message'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_active'], name='idx_customer_company_active'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone_number'], name='idx_customer_company_phone'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'phone_number'), name='unique_customer_phone_per_company'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'message_timestamp'], name='idx_message_conversation_time'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction', 'message_timestamp'], name='idx_message_direction_time'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'message_timestamp'], name='idx_message_type_time'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['message', 'is_active'], name='idx_media_message_active'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['meta_media_id'], name='idx_media_meta_id'),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['is_stored'], name='idx_media_stored'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['user', 'is_read'], name='idx_read_state_user_read'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['conversation', 'user'], name='idx_readstate_conv_user'),
        ),
        migrations.AddConstraint(
            model_name='conversationreadstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_read_state_per_user'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['whatsapp_number', 'is_active'], name='idx_conversation_number_active'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['whatsapp_number', 'last_message_at'], name='idx_conversation_number_last'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', 'last_message_at'], name='idx_conversation_customer_last'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('whatsapp_number', 'customer'), name='unique_conversation_per_number_customer'),
        ),
    ]
