# Generated by Django 6.1 on 2026-08-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_remove_message_edited_message_message_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='context_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_events', to='whatsapp.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_context_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['meta_context_message_id'], name='idx_message_context_meta'),
        ),
        migrations.AddConstraint(
            model_name='mediaattachment',
            constraint=models.UniqueConstraint(fields=('message', 'meta_media_id'), name='unique_media_per_message'),
        ),
    ]
