# Generated by Django 6.1 on 2026-08-23 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_message_content_data_message_context_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaattachment',
            name='retrieval_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='storage_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='storage_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STORED', 'Stored'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['storage_status'], name='idx_media_storage_status'),
        ),
    ]
