# Generated by Django 6.1 on 2026-08-24 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_mediaattachment_retrieval_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_template_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('PENDING_DELETION', 'Pending Deletion'), ('IN_APPEAL', 'In Appeal'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('parameter_format', models.CharField(choices=[('POSITIONAL', 'Positional'), ('NAMED', 'Named')], default='POSITIONAL', max_length=20)),
                ('components', models.JSONField(blank=True, default=list)),
                ('quality_score', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_available_in_meta', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('removed_from_meta_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_business_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'db_table': 'whatsapp_message_template',
                'ordering': ['name', 'language'],
                'indexes': [models.Index(fields=['whatsapp_business_account', 'status'], name='idx_tpl_waba_status'), models.Index(fields=['whatsapp_business_account', 'category'], name='idx_tpl_waba_category'), models.Index(fields=['whatsapp_business_account', 'language'], name='idx_tpl_waba_language'), models.Index(fields=['whatsapp_business_account', 'is_available_in_meta'], name='idx_tpl_waba_available')],
                'constraints': [models.UniqueConstraint(fields=('whatsapp_business_account', 'name', 'language'), name='unique_waba_template_language')],
            },
        ),
    ]
