# Generated by Django 6.1 on 2026-09-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('whatsapp', '0005_whatsappmessagetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metaintegration',
            name='unique_company_meta_app',
        ),
        migrations.RemoveIndex(
            model_name='metaintegration',
            name='idx_meta_webhook_key',
        ),
        migrations.AlterField(
            model_name='numberassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_number_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='metaintegration',
            constraint=models.UniqueConstraint(fields=('company',), name='unique_meta_integration_per_company'),
        ),
        migrations.RemoveField(
            model_name='metaintegration',
            name='credential_reference',
        ),
        migrations.RemoveField(
            model_name='metaintegration',
            name='meta_app_id',
        ),
        migrations.RemoveField(
            model_name='metaintegration',
            name='webhook_key',
        ),
    ]
