# Generated by Django 6.1 on 2026-09-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_remove_meta_integration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whatsappbusinessaccount',
            name='idx_waba_meta_active',
        ),
    ]
