# Generated by Django 6.1 on 2026-09-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_accessuser_created_by_accessuser_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMINISTRATOR', 'Super Administrator'), ('ADMINISTRATOR', 'Administrator'), ('MONITOR', 'Monitor'), ('MEMBER', 'Member')], max_length=25),
        ),
    ]
